name: Deploy Static Site

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject Secrets into JS
        run: |
          echo "Injecting secrets into JS file"
          mkdir -p dist
          echo "window.TOKEN='${{ secrets.TOKEN }}';" > dist/secrets.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
